packages:
  # UI, runners, adapters, server, demos
  - "packages/*"
  - "ui/*"
  - "runners/*"
  - "adapters/*"
  - "server/*"
  - "demos/*"

  # flowise - for now, we don't need components and ui
  - "monorepos/flowise/packages/server"
  - "monorepos/flowise/packages/components"
  # - "monorepos/flowise/packages/ui"

  # @vercel/ai
  - "monorepos/ai/packages/core"
  - "monorepos/ai/tools/*"