"use client";
import type { Metadata } from "next";
import "./globals.css";
import "@proompter/react/styles/global";
import { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const allThemes = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  "dim",
  "nord",
  "sunset",
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [themeNumber, setThemeNumber] = useState(0);
  useEffect(() => {}, []);

  return (
    <html
      onKeyUp={(e) => {
        if (e.key == "t" && e.ctrlKey) {
          setThemeNumber((themeNumber + 1) % allThemes.length);
        }
      }}
      lang="en"
      data-theme={allThemes[themeNumber]}
    >
      <body>{children}</body>
    </html>
  );
}
